global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Go API Service
  - job_name: 'go-api'
    static_configs:
      - targets: ['go-app:8080']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Python CPAG Generator
  - job_name: 'python-cpag-generator'
    static_configs:
      - targets: ['python-cpag-generator:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # RabbitMQ
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']
    scrape_interval: 30s

  # Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s

  # Neo4j
  - job_name: 'neo4j'
    static_configs:
      - targets: ['neo4j:2004']
    scrape_interval: 30s

  # InfluxDB
  - job_name: 'influxdb'
    static_configs:
      - targets: ['influxdb:8086']
    scrape_interval: 30s

  # Celery Workers
  - job_name: 'celery-workers'
    static_configs:
      - targets: ['celery-worker:8888']
    scrape_interval: 15s

  # Flower Monitoring
  - job_name: 'flower'
    static_configs:
      - targets: ['flower:5555']
    scrape_interval: 30s

  # Node Exporter (if available)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s
